-- ============================================================
-- Migration: Monthly Commitments (Bills)
-- Date: 2026-05-14
-- Feature: Personal Space → Bills tab
--
-- Two tables:
--   commitments          — recurring bill definitions (the "contract")
--   commitment_payments  — monthly payment records per commitment
-- ============================================================

-- ── 1. commitments ──────────────────────────────────────────
-- One row per recurring bill the user wants to track.
-- Examples: car loan, house rental, TNB, Astro, gym membership.

CREATE TABLE IF NOT EXISTS commitments (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID        NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  space_id     UUID        NOT NULL REFERENCES spaces(id)   ON DELETE CASCADE,

  name         TEXT        NOT NULL,           -- "Proton X50 Loan", "Sewa Rumah", "TNB"
  amount       NUMERIC(12,2) NOT NULL,          -- fixed monthly amount
  currency     TEXT        NOT NULL DEFAULT 'MYR',

  -- Category determines the icon and grouping in the report
  category     TEXT        NOT NULL
    CHECK (category IN (
      'LOAN',          -- Car loan, personal loan, PTPTN
      'MORTGAGE',      -- House mortgage / rumah loan
      'RENTAL',        -- House rental, office rental
      'UTILITIES',     -- TNB, Syabas, Gas
      'INSURANCE',     -- Life, medical, car insurance
      'SUBSCRIPTION',  -- Astro, Netflix, Spotify, gym
      'EDUCATION',     -- School fees, tuition
      'OTHER'          -- Anything else
    )),

  due_day      INTEGER     NOT NULL CHECK (due_day BETWEEN 1 AND 31),
  -- Day of month payment is due. 31 = last day of month (handled in app logic).

  start_date   DATE        NOT NULL,           -- When this commitment started
  end_date     DATE,                           -- NULL = ongoing indefinitely
                                               -- e.g., loan end date

  is_active    BOOLEAN     NOT NULL DEFAULT TRUE,
  -- FALSE = commitment ended / cancelled. Kept for history.

  notes        TEXT,                           -- Internal notes, reference numbers

  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── 2. commitment_payments ───────────────────────────────────
-- One row per month per commitment.
-- Auto-generated by the app at the start of each month for active commitments.
-- User marks each row as PAID, MISSED, or PARTIAL.

CREATE TABLE IF NOT EXISTS commitment_payments (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  commitment_id   UUID        NOT NULL REFERENCES commitments(id) ON DELETE CASCADE,

  year            INTEGER     NOT NULL,
  month           INTEGER     NOT NULL CHECK (month BETWEEN 1 AND 12),
  -- Unique per commitment per calendar month
  UNIQUE (commitment_id, year, month),

  due_date        DATE        NOT NULL,        -- Calculated from commitment.due_day + year/month
  expected_amount NUMERIC(12,2) NOT NULL,      -- Snapshot of commitment.amount at time of creation

  status          TEXT        NOT NULL DEFAULT 'PENDING'
    CHECK (status IN (
      'PENDING',    -- Not yet due or awaiting user action
      'PAID',       -- Paid in full
      'PARTIAL',    -- Partial payment made
      'MISSED',     -- Due date passed, not paid
      'SKIPPED'     -- User deliberately skipped (e.g., waived month)
    )),

  paid_date       DATE,                        -- Date user marked as paid
  paid_amount     NUMERIC(12,2),               -- Actual amount paid (may differ if partial)

  notes           TEXT,                        -- e.g., "paid early", "receipt ref XYZ"

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── 3. Indexes ───────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_commitments_user_id
  ON commitments (user_id);

CREATE INDEX IF NOT EXISTS idx_commitments_space_id
  ON commitments (space_id);

CREATE INDEX IF NOT EXISTS idx_commitments_active
  ON commitments (user_id, is_active);

CREATE INDEX IF NOT EXISTS idx_commitment_payments_commitment_id
  ON commitment_payments (commitment_id);

CREATE INDEX IF NOT EXISTS idx_commitment_payments_year_month
  ON commitment_payments (commitment_id, year, month);

CREATE INDEX IF NOT EXISTS idx_commitment_payments_status
  ON commitment_payments (status, due_date);

-- ── 4. updated_at auto-update triggers ──────────────────────

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_commitments_updated_at ON commitments;
CREATE TRIGGER set_commitments_updated_at
  BEFORE UPDATE ON commitments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS set_commitment_payments_updated_at ON commitment_payments;
CREATE TRIGGER set_commitment_payments_updated_at
  BEFORE UPDATE ON commitment_payments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ── 5. Row Level Security ────────────────────────────────────

ALTER TABLE commitments         ENABLE ROW LEVEL SECURITY;
ALTER TABLE commitment_payments ENABLE ROW LEVEL SECURITY;

-- commitments: owner only
CREATE POLICY "commitments_select_own"
  ON commitments FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "commitments_insert_own"
  ON commitments FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "commitments_update_own"
  ON commitments FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "commitments_delete_own"
  ON commitments FOR DELETE
  USING (auth.uid() = user_id);

-- commitment_payments: owner only (via join to commitments)
CREATE POLICY "commitment_payments_select_own"
  ON commitment_payments FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM commitments c
      WHERE c.id = commitment_payments.commitment_id
        AND c.user_id = auth.uid()
    )
  );

CREATE POLICY "commitment_payments_insert_own"
  ON commitment_payments FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM commitments c
      WHERE c.id = commitment_payments.commitment_id
        AND c.user_id = auth.uid()
    )
  );

CREATE POLICY "commitment_payments_update_own"
  ON commitment_payments FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM commitments c
      WHERE c.id = commitment_payments.commitment_id
        AND c.user_id = auth.uid()
    )
  );

-- ── 6. Backfill note ────────────────────────────────────────
-- No backfill needed — new feature, no existing data.
-- Run this migration in Supabase Dashboard → SQL Editor.
