'use client'
// apps/admin/app/(protected)/exports/ExportsClient.tsx

import { useMemo, useState } from 'react'

type Org = { id: string; name: string; display_name: string | null }

type ExportJob = {
  id: string
  org_id: string
  user_id: string
  format: string
  status: 'PENDING' | 'RUNNING' | 'DONE' | 'FAILED'
  file_url: string | null
  row_count: number | null
  error_message: string | null
  filters: Record<string, unknown> | null
  template_id: string | null
  created_at: string
  completed_at: string | null
  profiles: { display_name: string | null; email: string | null } | null
  organizations: { name: string; display_name: string | null } | null
  report_templates: { name: string } | null
}

function fmtDateTime(iso: string | null) {
  if (!iso) return '—'
  return new Date(iso).toLocaleString('en-MY', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit',
    timeZone: 'Asia/Kuala_Lumpur',
  })
}

function StatusBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    DONE:    'bg-green-50 text-green-700 border border-green-200',
    FAILED:  'bg-red-50 text-red-700 border border-red-200',
    RUNNING: 'bg-blue-50 text-blue-700 border border-blue-200',
    PENDING: 'bg-gray-100 text-gray-500 border border-gray-200',
  }
  const icons: Record<string, string> = {
    DONE: '✓', FAILED: '✕', RUNNING: '⏳', PENDING: '⏸',
  }
  return (
    <span className={`inline-flex items-center gap-1 px-2 py-0.5 rounded text-xs font-semibold ${styles[status] ?? 'bg-gray-100 text-gray-500'}`}>
      {icons[status]}{status}
    </span>
  )
}

function FormatBadge({ format }: { format: string }) {
  const colors: Record<string, string> = {
    CSV:  'bg-emerald-50 text-emerald-700',
    XLSX: 'bg-teal-50 text-teal-700',
    PDF:  'bg-rose-50 text-rose-700',
  }
  return (
    <span className={`inline-flex px-1.5 py-0.5 rounded text-xs font-bold ${colors[format] ?? 'bg-gray-100 text-gray-600'}`}>
      {format}
    </span>
  )
}

export default function ExportsClient({
  initialJobs,
  orgs,
}: {
  initialJobs: ExportJob[]
  orgs: Org[]
}) {
  const [jobs,    setJobs]    = useState(initialJobs)
  const [loading, setLoading] = useState(false)

  const [statusFilter, setStatusFilter] = useState('')
  const [orgFilter,    setOrgFilter]    = useState('')
  const [formatFilter, setFormatFilter] = useState('')
  const [from,         setFrom]         = useState('')
  const [to,           setTo]           = useState('')
  const [expandedId,   setExpandedId]   = useState<string | null>(null)

  const filtered = useMemo(() => {
    return jobs.filter(j => {
      if (statusFilter && j.status !== statusFilter) return false
      if (orgFilter    && j.org_id !== orgFilter)    return false
      if (formatFilter && j.format !== formatFilter)  return false
      if (from && j.created_at < from) return false
      if (to   && j.created_at > to + 'T23:59:59Z') return false
      return true
    })
  }, [jobs, statusFilter, orgFilter, formatFilter, from, to])

  async function fetchJobs() {
    setLoading(true)
    try {
      const params = new URLSearchParams()
      if (statusFilter) params.set('status', statusFilter)
      if (orgFilter)    params.set('org_id', orgFilter)
      if (formatFilter) params.set('format', formatFilter)
      if (from)         params.set('from', from)
      if (to)           params.set('to', to)
      params.set('page_size', '200')

      const res = await fetch(`/api/admin/export-jobs?${params}`)
      const json = await res.json()
      if (res.ok) setJobs(json.jobs ?? [])
    } catch { /* keep existing */ }
    finally { setLoading(false) }
  }

  // Summary counts
  const doneCount    = filtered.filter(j => j.status === 'DONE').length
  const failedCount  = filtered.filter(j => j.status === 'FAILED').length
  const pendingCount = filtered.filter(j => j.status === 'PENDING' || j.status === 'RUNNING').length

  return (
    <div className="space-y-5">

      {/* Header */}
      <div>
        <h1 className="text-xl font-bold text-gray-900">Export Jobs</h1>
        <p className="text-sm text-gray-500 mt-0.5">All export jobs generated by users across all organisations.</p>
      </div>

      {/* Summary cards */}
      <div className="grid grid-cols-3 gap-4">
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <div className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Completed</div>
          <div className="text-2xl font-bold text-green-600 mt-1">{doneCount}</div>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <div className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Failed</div>
          <div className="text-2xl font-bold text-red-500 mt-1">{failedCount}</div>
        </div>
        <div className="bg-white rounded-xl border border-gray-200 p-4">
          <div className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Pending / Running</div>
          <div className="text-2xl font-bold text-gray-500 mt-1">{pendingCount}</div>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white rounded-xl border border-gray-200 p-4 space-y-3">
        <div className="grid grid-cols-2 md:grid-cols-5 gap-3">
          <div>
            <label className="block text-xs font-medium text-gray-500 mb-1">Status</label>
            <select value={statusFilter} onChange={e => setStatusFilter(e.target.value)}
              className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:outline-none">
              <option value="">All statuses</option>
              <option value="DONE">Done</option>
              <option value="FAILED">Failed</option>
              <option value="RUNNING">Running</option>
              <option value="PENDING">Pending</option>
            </select>
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-500 mb-1">Format</label>
            <select value={formatFilter} onChange={e => setFormatFilter(e.target.value)}
              className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:outline-none">
              <option value="">All formats</option>
              <option value="CSV">CSV</option>
              <option value="XLSX">XLSX</option>
              <option value="PDF">PDF</option>
            </select>
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-500 mb-1">Organisation</label>
            <select value={orgFilter} onChange={e => setOrgFilter(e.target.value)}
              className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm bg-white focus:outline-none">
              <option value="">All orgs</option>
              {orgs.map(o => <option key={o.id} value={o.id}>{o.display_name ?? o.name}</option>)}
            </select>
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-500 mb-1">Date from</label>
            <input type="date" value={from} onChange={e => setFrom(e.target.value)}
              className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none" />
          </div>
          <div>
            <label className="block text-xs font-medium text-gray-500 mb-1">Date to</label>
            <input type="date" value={to} onChange={e => setTo(e.target.value)}
              className="w-full px-3 py-2 border border-gray-200 rounded-lg text-sm focus:outline-none" />
          </div>
        </div>
        <div className="flex gap-3">
          <button onClick={fetchJobs} disabled={loading}
            className="px-4 py-2 bg-gray-900 text-white text-sm font-medium rounded-lg disabled:opacity-50">
            {loading ? 'Loading…' : 'Apply Filters'}
          </button>
          <button onClick={() => { setStatusFilter(''); setOrgFilter(''); setFormatFilter(''); setFrom(''); setTo('') }}
            className="px-4 py-2 bg-gray-100 text-gray-600 text-sm font-medium rounded-lg">
            Clear
          </button>
        </div>
      </div>

      {/* Jobs table */}
      <div className="bg-white rounded-xl border border-gray-200 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-gray-100 bg-gray-50">
                <th className="text-left px-5 py-3 text-xs font-medium text-gray-500 uppercase">Created</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">Staff</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">Organisation</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">Format</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">Template</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">Status</th>
                <th className="text-right px-4 py-3 text-xs font-medium text-gray-500 uppercase">Rows</th>
                <th className="text-left px-4 py-3 text-xs font-medium text-gray-500 uppercase">Completed</th>
                <th className="px-4 py-3" />
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {filtered.length === 0 && (
                <tr>
                  <td colSpan={9} className="px-5 py-10 text-center text-sm text-gray-400">
                    No export jobs found.
                  </td>
                </tr>
              )}
              {filtered.map(job => {
                const user     = Array.isArray(job.profiles)         ? job.profiles[0]         : job.profiles
                const org      = Array.isArray(job.organizations)    ? job.organizations[0]    : job.organizations
                const template = Array.isArray(job.report_templates) ? job.report_templates[0] : job.report_templates
                const isExpanded = expandedId === job.id

                return (
                  <>
                    <tr key={job.id} className="hover:bg-gray-50">
                      <td className="px-5 py-3 text-xs text-gray-500 whitespace-nowrap">
                        {fmtDateTime(job.created_at)}
                      </td>
                      <td className="px-4 py-3">
                        <div className="text-xs font-medium text-gray-800">{user?.display_name ?? '—'}</div>
                        <div className="text-xs text-gray-400">{user?.email ?? '—'}</div>
                      </td>
                      <td className="px-4 py-3 text-xs text-gray-600">
                        {(org as { display_name?: string | null; name: string } | null)?.display_name ?? (org as { name: string } | null)?.name ?? '—'}
                      </td>
                      <td className="px-4 py-3"><FormatBadge format={job.format} /></td>
                      <td className="px-4 py-3 text-xs text-gray-500">
                        {(template as { name: string } | null)?.name ?? <span className="text-gray-300">—</span>}
                      </td>
                      <td className="px-4 py-3"><StatusBadge status={job.status} /></td>
                      <td className="px-4 py-3 text-right text-xs text-gray-600">
                        {job.row_count ?? '—'}
                      </td>
                      <td className="px-4 py-3 text-xs text-gray-400 whitespace-nowrap">
                        {fmtDateTime(job.completed_at)}
                      </td>
                      <td className="px-4 py-3 text-right">
                        <div className="flex items-center justify-end gap-2">
                          {job.file_url && job.status === 'DONE' && (
                            <a href={job.file_url} target="_blank" rel="noopener noreferrer"
                              className="text-xs font-medium text-green-600 hover:text-green-800">
                              ↓ File
                            </a>
                          )}
                          {job.filters && (
                            <button onClick={() => setExpandedId(isExpanded ? null : job.id)}
                              className="text-xs text-blue-600 hover:text-blue-800">
                              {isExpanded ? 'Hide' : 'Filters'}
                            </button>
                          )}
                        </div>
                      </td>
                    </tr>

                    {/* Error message row */}
                    {job.status === 'FAILED' && job.error_message && (
                      <tr key={`${job.id}-err`} className="bg-red-50">
                        <td colSpan={9} className="px-5 py-2 text-xs text-red-600">
                          ✕ {job.error_message}
                        </td>
                      </tr>
                    )}

                    {/* Filters detail row */}
                    {isExpanded && job.filters && (
                      <tr key={`${job.id}-filters`} className="bg-gray-50">
                        <td colSpan={9} className="px-5 py-3">
                          <pre className="text-xs text-gray-600 overflow-x-auto whitespace-pre-wrap bg-white border border-gray-100 rounded p-3 max-h-32">
                            {JSON.stringify(job.filters, null, 2)}
                          </pre>
                        </td>
                      </tr>
                    )}
                  </>
                )
              })}
            </tbody>
          </table>
        </div>
        <div className="px-5 py-3 border-t border-gray-100 text-xs text-gray-400">
          {filtered.length} job{filtered.length !== 1 ? 's' : ''} shown
        </div>
      </div>
    </div>
  )
}
